# Generated by Django 5.1.6 on 2025-02-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("student_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(blank=True, max_length=50, null=True)),
                ("last_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("major", models.CharField(blank=True, max_length=50, null=True)),
                ("enrollment_year", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "student",
            },
        ),
    ]
